version: "3.2"

services:
  chain_one:
    build:
      context: .
      dockerfile: ./build.dockerfile.yml
    container_name: atocha-one
    image: atocha-protocol/atocha-node
    ports:
      - "8844:9944"
      - "8833:9933"
      - "31333:30333"
    volumes:
      - ./data/atocha/one:/data
    command: >
      atocha-node --chain /usr/local/bin/atocha-chain-local-test-spec-raw.json --name ato_one --execution Native --pruning archive
      --ws-external --rpc-external --rpc-cors=all --rpc-methods=Unsafe
      --prometheus-external --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
      --port 30333
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
      ---validator
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      atochain_network:
        ipv4_address: 172.30.1.2
  chain_two:
    container_name: atocha-two
    image: atocha-protocol/atocha-node
    ports:
      - "8845:9944"
      - "8834:9933"
      - "31334:30333"
    volumes:
      - ./data/atocha/two:/data
    command: >
      atocha-node --chain /usr/local/bin/atocha-chain-local-test-spec-raw.json --name ato_two --execution Native --pruning archive
      --ws-external --rpc-external --rpc-cors=all --rpc-methods=Unsafe
      --prometheus-external --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
      --port 30333
      --bootnodes /ip4/172.30.1.2/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      ---validator
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      atochain_network:
        ipv4_address: 172.30.1.3
  chain_three:
    container_name: atocha-three
    image: atocha-protocol/atocha-node
    ports:
      - "8846:9944"
      - "8835:9933"
      - "31335:30333"
    volumes:
      - ./data/atocha/three:/data
    command: >
      atocha-node --chain /usr/local/bin/atocha-chain-local-test-spec-raw.json --name ato_three --execution Native --pruning archive
      --ws-external --rpc-external --rpc-cors=all --rpc-methods=Unsafe
      --prometheus-external --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
      --port 30333
      --bootnodes /ip4/172.30.1.2/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      ---validator
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      atochain_network:
        ipv4_address: 172.30.1.4
  chain_four:
    container_name: atocha-four
    image: atocha-protocol/atocha-node
    ports:
      - "8847:9944"
      - "8836:9933"
      - "31336:30333"
    volumes:
      - ./data/atocha/four:/data
    command: >
      atocha-node --chain /usr/local/bin/atocha-chain-local-test-spec-raw.json --name ato_three --execution Native --pruning archive
      --ws-external --rpc-external --rpc-cors=all --rpc-methods=Unsafe
      --prometheus-external --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
      --port 30333
      --bootnodes /ip4/172.30.1.2/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      ---validator
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      atochain_network:
        ipv4_address: 172.30.1.5
networks:
  atochain_network:
    ipam:
      config:
          - subnet: "172.30.1.0/24"
